### ISSUE TITLE
The bot does not send reports to specified channel and does not allow me to run the command

### ISSUE THREAD

**Issue by NubbDev** [MrTigreroux/TigerReportsSupports#11]
The Bot when server starts or stop will promp this:
![image](https://user-images.githubusercontent.com/57550644/135664975-cb1c4c78-175b-4921-b7ce-01e59a49ed6c.png)

But when I try reporting someone in game, the report is stored but not sent in the channel

When I try running any bot commands like /tigerrepors t it says: 
![image](https://user-images.githubusercontent.com/57550644/135665155-617bf569-0baf-48d5-9db6-ef7bbea659d5.png)

But in my config I first set it up to keep the id
![image](https://user-images.githubusercontent.com/57550644/135665239-db9c3b74-8108-4a7b-bb60-ceefae745c4d.png)
and also the username
![image](https://user-images.githubusercontent.com/57550644/135671063-8a946389-55e0-4502-a0be-7409c2d784b9.png)

**Comment by Nuuby-Dev** [comment]
Config
`
TigerReportsSupports:
  Version: 1.7+ spigot
  Author: MrTigreroux
  Description: Adds supports to TigerReports plugin / Ajoute des supports au plugin TigerReports.
Config:
  Discord:
    Enabled: true
    
    Token: <bottoken>
    # Discord bot token / Token du bot Discord
    
    Channel: 893164125671272539
    # Text Channel ID for the alerts / Identifiant du canal texte pour les alertes
    
    Managers:
     - 704496986535100467
     - 401844809385508903
    # List of Discord users who can use /tigerreports command / Liste des utilisateurs du Discord qui peuvent utiliser la commande /tigerreports
    
    ServerInfo: yes
    # Display the server in alerts / Afficher le serveur dans les alertes
    
    Thumbnail: ""
    # Web link of the image displayed at the top right corner of the bot alerts / Lien internet de l'image affichée dans le coin supérieur droit des alertes du bot
    # Usable placeholders:    _Reporter_ and _Reported_
    
    PlayingStatus: ""
    # Set the played game message (the activity "Playing at ...") on Discord / Définit le jeu actuellement joué (l'activité "Joue à ...") sur Discord
    
    NotifyOnlyLocalReports: no
    # Notify with the Discord bot only the reports that are sent from the Spigot server where this TigerReportsSupports plugin is installed. Enabling this setting allows to install TigerReportsSupports plugin on all your Spigot servers, which is not necessary if you use BungeeCord but removes the necessity to have at least 1 connected player to receive BungeeCord notifications and therefore new reports / Informer, avec le bot Discord, uniquement des signalements envoyés depuis le serveur Spigot où ce plugin TigerReportsSupports est installé. En activant ce paramètre, le plugin TigerReportsSupports peut être installé sur tous les serveurs Spigot, ce qui n'est pas nécessaire si vous utilisez BungeeCord mais cela retire la nécessité d'avoir au moins 1 joueur connecté pour recevoir les notifications BungeeCord et donc les nouveaux signalements
`

**Comment by MrTigreroux** [comment]
Hello, there must be at least one player of the Spigot server in order for the bot to receive and therefore send report alerts. If the "Disconnected" message is sent, then no report alert will be sent because the plugin is disabled.
Managers must be configured like "pseudo#1234", not an id. I don't think you have a "@" in your discord pseudo, try to remove it. Your discord pseudo (username) is written at the bottom left corner of your Discord app, it can be different from your server pseudo.
