### ISSUE TITLE
It would be nice to mark as resolved and show in embed if the report was set to true, false or uncertain

### ISSUE THREAD

**Issue by thiagogebrimm** [MrTigreroux/TigerReportsSupports#12]
Currently it just shows that it has been resolved.

**Comment by MrTigreroux** [comment]
Ok, will add it when I find time, thank you for the suggestion.

**Comment by MrTigreroux** [comment]
Hello, I finally found time to implement your suggestion in new [version 1.6.3](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=441059) which requires new version 4.13.1 of TigerReports.
Thank you again for suggesting it.
