### ISSUE TITLE
Discord bot not working?

### ISSUE THREAD

**Issue by LaserXx** [MrTigreroux/TigerReportsSupports#16]
Hey, so I installed the discord plugin for tiger reports and I set everything up correctly. But for some reason, the bot won't go online. I made sure I followed all the steps you mentioned but it was still not working. Does it have to do with the < token > ?

**Comment by LaserXx** [comment]
It was indeed a bad copy paste from my config file. Should I remove the < > when putting my token?

**Comment by MrTigreroux** [comment]
Yes, and replace them with `"` or `'` if you have `"` in your token.
