### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Peps3k** [MrTigreroux/TigerReportsSupports#24]
I have a BungeeCord so I'm using more servers where I have TigerReportsSupports plugin (Connected via database).
Exactly what I want to fix is when I change report's status on server where I don't used /report then it doesn't changed on discord. I hope you understand and it will be great if you'll fix it. Thanks.

**Comment by MrTigreroux** [comment]
Hello, I think you missed this paragraph in the Installation section of the [plugin page](https://www.spigotmc.org/resources/tigerreportssupports.54612/):

![](https://i.imgur.com/KEKoCW4.png)

Let me know if you followed that instructions and it still doesn't work.

**Comment by Peps3k** [comment]
Oh I'm a little stupid :D I didn't see that. It works now and thank you ;)

**Comment by Peps3k** [comment]
I found a one thing which can be changed. When I set "NotifyOnlyLocalReports" to "no" so It works great but when is some report reported on the other server and I switch to another server then it sends the report message to the discord again and thats kinda annoying. Can you change or fix it somehow?

**Comment by MrTigreroux** [comment]
I'm not sure to understand.
If you configured `NotifyOnlyLocalReports` setting to "no", then you must install TigerReportsSupports on **<ins>only 1</ins> Spigot server**. You must know that this server will not be able to receive BungeeCord notifications (including those of reports) and therefore send Discord alerts if there is no player connected to that server. That means that all the reports done on other servers while there is no player on this server where you installed TigerReportsSupports won't be displayed in your Discord channel until one player join that server.

**Comment by Peps3k** [comment]
So I've put a TigerReportsSupports only on 1 Spigot server and it fixed my problem but another showed up. Now if I use **/report** on the server where TigerReportsSupports is not downloaded then it sends a message to the discord only when I switch to the server where is the TigerReportsSupports downloaded. How can I fix this?

**Comment by MrTigreroux** [comment]
That is exactly what I'm trying to explain you, and that I tried to explain in the paragraph that I gave you before.
There are 2 choices, both have advantages and disadvantages. You made one choice, but maybe you prefer to do the other. But you can't mix the choices: all the Spigot servers must be configured (for TigerReports and TigerReportsSupports) the same way.

**Comment by Peps3k** [comment]
Okay then what I have to set do if I want to do that like I wrote it before? It's complicated for me so I'm a little confused now.

**Comment by MrTigreroux** [comment]
I think that you want the second option:

![](https://i.imgur.com/YJTOPSl.png)

Install TigerReportsSupports on **<ins>all</ins> your Spigot servers**, with all that servers configured with **<ins>the same</ins>** `plugins/TigerReportsSupports/config.yml` file where `NotifyOnlyLocalReports` is set to `"yes"`.

**Comment by MrTigreroux** [comment]
This issue should be fixed in the new version [1.6.8](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=455633) of TigerReportsSupports and [5.0.13](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455632) of TigerReports.
Sorry for not understanding your problem before.

**Comment by Peps3k** [comment]
Okay. It's okay and thank you ;)
