### ISSUE TITLE
1.8 Hub server crashes after processing a report

### ISSUE THREAD

**Issue by nicholasveronico** [MrTigreroux/TigerReportsSupports#26]
Hello,

Every time I process a report on my 1.8 hubs, the server hangs and crashes. Here is the thread dump: https://mcpaste.io/869f47bba997c738

**Comment by MrTigreroux** [comment]
This problem should be fixed in the new [version 1.6.10](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=482477). Please tell me if it's not the case. Thank you again for reporting it.
