### ISSUE TITLE
bot dont send the report messages

### ISSUE THREAD

**Issue by FIREPawer** [MrTigreroux/TigerReportsSupports#27]

**Comment by MrTigreroux** [comment]
Hello,
* What version of TigerReports and TigerReportsSupports do you use ?
* What version of Spigot do you use (`/icanhasbukkit` command to see it) ?
* Have you correctly followed the instructions in the Installation section of [TigerReportsSupports presentation page](https://www.spigotmc.org/resources/tigerreportssupports.54612/) ? If so, do you see your Discord bot in the users list of your Discord server ?
* Have you tried to restart your Spigot server ?
* Do you have a BungeeCord network, and if so where have you installed TigerReportsSupports ?

**Comment by FIREPawer** [comment]
i use the 1.6.10 version
mohist 1.12.2-320 api version 1.12.2-R0.1-Snapshot, Forge version 14.23.5.2860
the plugin used to work 2 months ago and i followed the instructions perfectaly and the bot is online when the server is online
Yes, i restarted it more times
No, i dont have a bungeecord network

**Comment by MrTigreroux** [comment]
Ok thank you.
* What version of TigerReports do you use ?
* Do you have any error in the logs/console when you report a player ?
Is the [Connected message](https://github.com/MrTigreroux/TigerReportsSupports/blob/master/default-messages/english.yml#L2) message sent in the Discord channel by the bot when you restart your Spigot server ?

**Comment by FIREPawer** [comment]
5.1.3
No
![image](https://user-images.githubusercontent.com/69167292/210674483-809b3217-b85b-46f4-91ee-0d2cf5f0b0e4.png)

**Comment by MrTigreroux** [comment]
Ok, I would need more information to find the problem.
I would need you to do this:
* Stop your server
* Download that file: [logs.config.txt](https://github.com/MrTigreroux/TigerReports/files/10201656/logs.config.txt) and put it in the `plugins/TigerReports` folder of your server
* Rename the previous file to "logs.config"
* Restart your server
* Report yourself (`/report <player> <reason>` command)
* Copy all logs from "[TigerReports] Enabling..." to the report alert message and send them (hidding sensitive information like IPs) to me here or in [private message](https://www.spigotmc.org/conversations/add?to=MrTigreroux) on SpigotMC forum.
Thank you in advance.

**Comment by FIREPawer** [comment]
ok, i restarted the server after a day and it magicaly works again. thx anyway! 😃

**Comment by MrTigreroux** [comment]
Ok, maybe you have other plugins using Discord and there is a conflict depending on what plugin is launched first. In any case, if the problem still occurs please tell me and try with the logs as described before.
