### ISSUE TITLE
Reports Plugin cooldown

### ISSUE THREAD

**Issue by Odsodium** [MrTigreroux/TigerReportsSupports#4]
Hi there, I have an issue where the reports plugins cooldown is at 60 minutes after reporting someone. I have set it to 10 seconds
![image](https://user-images.githubusercontent.com/74337450/101263264-e6bb4c80-37a8-11eb-8707-fc3c4bb8ecb3.png)
Saved, reloaded the plugin and restarted the server but this message shows up
![image](https://user-images.githubusercontent.com/74337450/101263295-0bafbf80-37a9-11eb-899c-be5392af3f39.png)
Thanks

**Comment by MrTigreroux** [comment]
Hello, the report cooldown is applicated after the report and there is no retroaction. That is to say that if you got a cooldown of 60 minutes and then changed it in the config, you keep your cooldown of 60 minutes until it ends. To end a cooldown, use the command: `/reports stopcooldown <player>`.
If after changing the config.yml file, saving this file, typing `/reports reload` and then reporting a player you still get a cooldown of 60 minutes, please tell me.

**Comment by Odsodium** [comment]
Ok, thanks for your support
