### ISSUE TITLE
[Suggestion] Option to change the embed image

### ISSUE THREAD

**Issue by Amgelo563** [MrTigreroux/TigerReportsSupports#7]
Really awesome plugin, but I think it lacks a feature some people would like.

It would be useful to be able to change the embed image, it seems to me that specifically this [line of code](https://github.com/MrTigreroux/TigerReportsSupports/blob/master/TigerReportsSupports/src/fr/mrtigreroux/tigerreportssupports/bots/DiscordBot.java#L175) would need to be changed so it supports a config option.

This would make the addon more customizable, maybe even introducing some kind of system so it shows the head of the reporter/reported player, although just being able to change that link would be enough.

Thanks 👍

**Comment by MrTigreroux** [comment]
Hello,

As I explained in several reviews on SpigotMC, there is no credit in this plugin except this logo. I think that you can understand that I don't want to remove it.

Have a good day and thank you for your compliments.

**Comment by Amgelo563** [comment]
Maybe using an embed footer that says something like "System handled by TigerReports" which I think would fit nicely and still preserve the credits 👀, no problem if you won't though, it's understandable that you want to preserve the original credit.

**Comment by MrTigreroux** [comment]
Ok, I could add the footer and allow to edit the image at the top with a custom url and `_Reported_` et `_Reporter_` placeholders in order to be able to use websites like https://cravatar.eu/avatar/_Reported_/64.png to display the skull of the reported or reporter player. Thank you for the idea.

**Comment by MrTigreroux** [comment]
Added in new [version 1.6.2](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=422698). Thank you for suggesting it, have a good day.
