### ISSUE TITLE
Doesn't show report information

### ISSUE THREAD

**Issue by uIIIastic** [MrTigreroux/TigerReportsSupports#8]
![image](https://user-images.githubusercontent.com/90566637/132993839-3f22d7bb-2e4e-4c1f-b8b9-dbf416c60399.png)
Hello! Playholders do not work for me, and detailed information about the complaint is also not shown. How can I solve this problem?

Excuse my English, I don't know it very well.

**Comment by MrTigreroux** [comment]
If you are talking about the process message, there is only `_Id_` and `_Staff_` placeholders, all other informations are displayed in the report alert message that is normally above the process message. I don't see the point of adding those placeholders.

**Comment by uIIIastic** [comment]
why doesn't it show anything?

**Comment by uIIIastic** [comment]
![image](https://user-images.githubusercontent.com/90566637/132995463-ecc328ee-4b4f-4790-a9f3-6ac10aa5c845.png)
I don't see such a message, why? It must be turned on, if so, where?

**Comment by uIIIastic** [comment]
![image](https://user-images.githubusercontent.com/90566637/132996430-c652397c-cc7c-431c-908c-1389ef10b88d.png)
Now it shows information about new reports, but does not show information about completed reports.

**Comment by MrTigreroux** [comment]
I don't understand your problem. The "Report #28 has been processed by ScarePerson" message is just a message to indicate that the status of the previously sent report alert has changed. It is not meant to contain any particular data of the report because that data is already present in the report alert message.

**Comment by uIIIastic** [comment]
Before that, there was no information about the completion. The otte prefix did not change, it remained the same. Now everything has been decided, the problem has been solved. Thanks a lot! I have 5 stars!

**Comment by uIIIastic** [comment]
Before that, there was no information about the completion. The otte prefix did not change, it remained the same. Now everything has been decided, the problem has been solved. Thanks a lot! I have 5 stars!

**Comment by MrTigreroux** [comment]
Ok, happy to know it is now working and that you like the plugin. Good evening.
