### ISSUE TITLE
It would be nice to add it in the config to be able to customize the footer

### ISSUE THREAD

**Issue by thiagogebrimm** [MrTigreroux/TigerReportsSupports#9]
![image](https://user-images.githubusercontent.com/75040244/134820442-80f113b1-6944-4687-a61a-fda5138be3c2.png)

**Comment by MrTigreroux** [comment]
Hello, that is the only credit present in this plugin. This footer is displayed when you change the thumbnail (image at the top right corner). If you want to remove it, just keep the default thumbnail.
I'm sorry but I don't want to give the possibility to edit this footer.
